-- =============================================================================
-- Seed Vector DB Data for vector_db
-- =============================================================================
-- Purpose:  Set up pgvector extension, create the document_embeddings table,
--           insert ~50 sample equipment health documents with realistic content
--           and metadata, and create search functions (keyword, semantic, hybrid).
--
-- Target:   vector_db  (PostgreSQL 15+ with pgvector extension available)
-- Usage:    psql -d vector_db -f seed_vector_db.sql
-- Idempotent: Yes -- drops and recreates tables/functions.
-- =============================================================================

BEGIN;

-- ---------------------------------------------------------------------------
-- 1. Enable Extensions
-- ---------------------------------------------------------------------------
CREATE EXTENSION IF NOT EXISTS vector;
CREATE EXTENSION IF NOT EXISTS pg_trgm;
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- Verify pgvector
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_extension WHERE extname = 'vector') THEN
        RAISE EXCEPTION 'pgvector extension is not installed. Please install it first.';
    END IF;
    RAISE NOTICE 'pgvector extension verified.';
END $$;

-- ---------------------------------------------------------------------------
-- 2. Create document_embeddings table
-- ---------------------------------------------------------------------------
DROP TABLE IF EXISTS document_embeddings CASCADE;

CREATE TABLE document_embeddings (
    id                  TEXT PRIMARY KEY DEFAULT uuid_generate_v4()::TEXT,
    document_id         TEXT NOT NULL,
    source_file         TEXT,
    content             TEXT NOT NULL,
    content_hash        TEXT NOT NULL DEFAULT md5(random()::TEXT),
    document_type       TEXT NOT NULL,
    metadata            JSONB DEFAULT '{}'::JSONB,
    chunk_index         INTEGER DEFAULT 0,
    total_chunks        INTEGER DEFAULT 1,
    embedding           vector(1536),       -- NULL for now; embeddings added later via indexing pipeline
    created_at          TIMESTAMPTZ DEFAULT NOW(),
    updated_at          TIMESTAMPTZ DEFAULT NOW()
);

-- Auto-generated tsvector for full-text search
ALTER TABLE document_embeddings
ADD COLUMN IF NOT EXISTS content_tsv tsvector
GENERATED ALWAYS AS (to_tsvector('english', content)) STORED;

COMMENT ON TABLE document_embeddings IS
    'General-purpose document embeddings for RAG retrieval. '
    'Supports equipment_health, customer_360, and product_catalog document types.';

-- ---------------------------------------------------------------------------
-- 3. Create Indexes
-- ---------------------------------------------------------------------------

-- HNSW vector index (cosine similarity) -- will activate once embeddings are populated
CREATE INDEX IF NOT EXISTS idx_document_embedding_hnsw
ON document_embeddings
USING hnsw (embedding vector_cosine_ops)
WITH (m = 16, ef_construction = 200);

-- Full-text search GIN index on tsvector
CREATE INDEX IF NOT EXISTS idx_document_fts
ON document_embeddings
USING gin (content_tsv);

-- JSONB metadata GIN index for filtered queries
CREATE INDEX IF NOT EXISTS idx_document_metadata_gin
ON document_embeddings
USING gin (metadata jsonb_path_ops);

-- B-tree indexes for common lookups
CREATE INDEX IF NOT EXISTS idx_document_doc_id
ON document_embeddings (document_id);

CREATE INDEX IF NOT EXISTS idx_document_type
ON document_embeddings (document_type);

-- ---------------------------------------------------------------------------
-- 4. Insert ~50 sample equipment health documents
-- ---------------------------------------------------------------------------
-- These simulate the RAG documents generated by chunk_for_rag.py's
-- EquipmentHealthGenerator class. Each document describes one equipment's
-- health status, sensor readings, risk factors, and maintenance recommendations.

INSERT INTO document_embeddings (id, document_id, source_file, content, content_hash, document_type, metadata)
VALUES

-- ===== Low Risk Equipment (35 documents) =====

('eh-doc-001', 'EQ-1100-A-001', 'rag-documents/equipment_health/EQ-1100-A-001.md',
'# Equipment Health Report: EQ-1100-A-001

## Overview
- **Equipment ID:** EQ-1100-A-001
- **Plant:** 1100 (Primary Manufacturing)
- **Production Line:** LINE-A
- **Health Score:** 94.5 / 100
- **Failure Risk:** Low
- **Failure Probability:** 0.0312
- **Estimated Remaining Useful Life:** 342 days

## Sensor Summary
| Sensor | Value | Status |
|--------|-------|--------|
| Temperature | 42.3 °C | NORMAL |
| Vibration | 1.8 mm/s | NORMAL |
| Pressure | 4.5 bar | NORMAL |
| Humidity | 45.2 %RH | NORMAL |
| Flow Rate | 128.4 L/min | NORMAL |
| Power | 3.2 kW | NORMAL |

## Anomalies (Last 30 Days)
No anomalies detected. All sensor readings within normal operating ranges.

## Recommended Action
Continue routine monitoring. All parameters nominal. Next scheduled maintenance: 2026-06-15.',
md5('EQ-1100-A-001-health'), 'equipment_health',
'{"equipment_id": "EQ-1100-A-001", "plant_code": "1100", "production_line": "LINE-A", "health_score": 94.5, "failure_risk": "Low", "report_date": "2026-03-01"}'::JSONB),

('eh-doc-002', 'EQ-1100-A-002', 'rag-documents/equipment_health/EQ-1100-A-002.md',
'# Equipment Health Report: EQ-1100-A-002

## Overview
- **Equipment ID:** EQ-1100-A-002
- **Plant:** 1100 (Primary Manufacturing)
- **Production Line:** LINE-A
- **Health Score:** 91.2 / 100
- **Failure Risk:** Low
- **Failure Probability:** 0.0489
- **Estimated Remaining Useful Life:** 298 days

## Sensor Summary
| Sensor | Value | Status |
|--------|-------|--------|
| Temperature | 44.1 °C | NORMAL |
| Vibration | 2.1 mm/s | NORMAL |
| Pressure | 5.0 bar | NORMAL |
| Humidity | 48.7 %RH | NORMAL |
| Flow Rate | 115.9 L/min | NORMAL |
| Power | 4.1 kW | NORMAL |

## Anomalies (Last 30 Days)
1 anomaly detected: minor temperature spike on 2026-02-18 (52.1 °C, resolved within 15 minutes).

## Recommended Action
Continue routine monitoring. Standard preventive maintenance per schedule.',
md5('EQ-1100-A-002-health'), 'equipment_health',
'{"equipment_id": "EQ-1100-A-002", "plant_code": "1100", "production_line": "LINE-A", "health_score": 91.2, "failure_risk": "Low", "report_date": "2026-03-01"}'::JSONB),

('eh-doc-003', 'EQ-1100-B-001', 'rag-documents/equipment_health/EQ-1100-B-001.md',
'# Equipment Health Report: EQ-1100-B-001

## Overview
- **Equipment ID:** EQ-1100-B-001
- **Plant:** 1100 (Primary Manufacturing)
- **Production Line:** LINE-B
- **Health Score:** 88.7 / 100
- **Failure Risk:** Low
- **Failure Probability:** 0.0621
- **Estimated Remaining Useful Life:** 267 days

## Sensor Summary
All sensors reading within normal operating ranges. Temperature averaging 43.8 °C, vibration at 2.3 mm/s, pressure stable at 4.8 bar.

## Recommended Action
No action required. Equipment operating within normal range. Routine inspection at next planned downtime.',
md5('EQ-1100-B-001-health'), 'equipment_health',
'{"equipment_id": "EQ-1100-B-001", "plant_code": "1100", "production_line": "LINE-B", "health_score": 88.7, "failure_risk": "Low", "report_date": "2026-03-01"}'::JSONB),

('eh-doc-004', 'EQ-1100-B-003', 'rag-documents/equipment_health/EQ-1100-B-003.md',
'# Equipment Health Report: EQ-1100-B-003

## Overview
- **Equipment ID:** EQ-1100-B-003
- **Plant:** 1100 (Primary Manufacturing)
- **Production Line:** LINE-B
- **Health Score:** 96.1 / 100
- **Failure Risk:** Low
- **Failure Probability:** 0.0198
- **Estimated Remaining Useful Life:** 401 days

## Sensor Summary
Excellent condition across all sensors. Recently maintained on 2026-01-20. All readings well within normal ranges.

## Recommended Action
Continue routine monitoring. All parameters nominal.',
md5('EQ-1100-B-003-health'), 'equipment_health',
'{"equipment_id": "EQ-1100-B-003", "plant_code": "1100", "production_line": "LINE-B", "health_score": 96.1, "failure_risk": "Low", "report_date": "2026-03-01"}'::JSONB),

('eh-doc-005', 'EQ-1100-C-005', 'rag-documents/equipment_health/EQ-1100-C-005.md',
'# Equipment Health Report: EQ-1100-C-005

## Overview
- **Equipment ID:** EQ-1100-C-005
- **Plant:** 1100 (Primary Manufacturing)
- **Production Line:** LINE-C
- **Health Score:** 85.3 / 100
- **Failure Risk:** Low
- **Failure Probability:** 0.0834
- **Estimated Remaining Useful Life:** 215 days

## Sensor Summary
Temperature slightly elevated at 49.2 °C (within normal range). Other sensors nominal.

## Recommended Action
Standard preventive maintenance per schedule. Monitor temperature trend over next 2 weeks.',
md5('EQ-1100-C-005-health'), 'equipment_health',
'{"equipment_id": "EQ-1100-C-005", "plant_code": "1100", "production_line": "LINE-C", "health_score": 85.3, "failure_risk": "Low", "report_date": "2026-03-01"}'::JSONB),

('eh-doc-006', 'EQ-1100-D-002', 'rag-documents/equipment_health/EQ-1100-D-002.md',
'# Equipment Health Report: EQ-1100-D-002

## Overview
- **Equipment ID:** EQ-1100-D-002
- **Plant:** 1100 (Primary Manufacturing)
- **Production Line:** LINE-D
- **Health Score:** 92.8 / 100
- **Failure Risk:** Low
- **Failure Probability:** 0.0401
- **Estimated Remaining Useful Life:** 315 days

## Sensor Summary
All sensors nominal. Vibration steady at 1.6 mm/s. Power consumption stable at 2.9 kW.

## Recommended Action
Continue routine monitoring. Equipment in excellent operating condition.',
md5('EQ-1100-D-002-health'), 'equipment_health',
'{"equipment_id": "EQ-1100-D-002", "plant_code": "1100", "production_line": "LINE-D", "health_score": 92.8, "failure_risk": "Low", "report_date": "2026-03-01"}'::JSONB),

('eh-doc-007', 'EQ-1200-A-001', 'rag-documents/equipment_health/EQ-1200-A-001.md',
'# Equipment Health Report: EQ-1200-A-001

## Overview
- **Equipment ID:** EQ-1200-A-001
- **Plant:** 1200 (Secondary Manufacturing)
- **Production Line:** LINE-A
- **Health Score:** 89.4 / 100
- **Failure Risk:** Low
- **Failure Probability:** 0.0567
- **Estimated Remaining Useful Life:** 280 days

## Sensor Summary
Readings within normal ranges. Humidity slightly above average at 55.3 %RH but within acceptable limits. Flow rate stable at 142.7 L/min.

## Recommended Action
Routine inspection at next planned downtime. Monitor humidity sensor for calibration drift.',
md5('EQ-1200-A-001-health'), 'equipment_health',
'{"equipment_id": "EQ-1200-A-001", "plant_code": "1200", "production_line": "LINE-A", "health_score": 89.4, "failure_risk": "Low", "report_date": "2026-03-01"}'::JSONB),

('eh-doc-008', 'EQ-1200-A-004', 'rag-documents/equipment_health/EQ-1200-A-004.md',
'# Equipment Health Report: EQ-1200-A-004

## Overview
- **Equipment ID:** EQ-1200-A-004
- **Plant:** 1200 (Secondary Manufacturing)
- **Production Line:** LINE-A
- **Health Score:** 93.6 / 100
- **Failure Risk:** Low
- **Failure Probability:** 0.0345
- **Estimated Remaining Useful Life:** 330 days

## Sensor Summary
All parameters nominal. Recently completed preventive maintenance on 2026-02-05. Equipment performing optimally.

## Recommended Action
No action required. Equipment operating within normal range.',
md5('EQ-1200-A-004-health'), 'equipment_health',
'{"equipment_id": "EQ-1200-A-004", "plant_code": "1200", "production_line": "LINE-A", "health_score": 93.6, "failure_risk": "Low", "report_date": "2026-03-01"}'::JSONB),

('eh-doc-009', 'EQ-1200-B-002', 'rag-documents/equipment_health/EQ-1200-B-002.md',
'# Equipment Health Report: EQ-1200-B-002

## Overview
- **Equipment ID:** EQ-1200-B-002
- **Plant:** 1200 (Secondary Manufacturing)
- **Production Line:** LINE-B
- **Health Score:** 87.1 / 100
- **Failure Risk:** Low
- **Failure Probability:** 0.0712

## Sensor Summary
Minor vibration uptick noted (2.9 mm/s) but still within normal range. Temperature stable at 41.5 °C.

## Recommended Action
Continue routine monitoring. Schedule lubrication during next planned downtime.',
md5('EQ-1200-B-002-health'), 'equipment_health',
'{"equipment_id": "EQ-1200-B-002", "plant_code": "1200", "production_line": "LINE-B", "health_score": 87.1, "failure_risk": "Low", "report_date": "2026-03-01"}'::JSONB),

('eh-doc-010', 'EQ-1200-C-001', 'rag-documents/equipment_health/EQ-1200-C-001.md',
'# Equipment Health Report: EQ-1200-C-001

## Overview
- **Equipment ID:** EQ-1200-C-001
- **Plant:** 1200 (Secondary Manufacturing)
- **Production Line:** LINE-C
- **Health Score:** 90.5 / 100
- **Failure Risk:** Low
- **Failure Probability:** 0.0523

## Sensor Summary
All sensors reading within normal operating ranges. Pressure stable at 5.2 bar. Power at 3.8 kW.

## Recommended Action
Standard preventive maintenance per schedule.',
md5('EQ-1200-C-001-health'), 'equipment_health',
'{"equipment_id": "EQ-1200-C-001", "plant_code": "1200", "production_line": "LINE-C", "health_score": 90.5, "failure_risk": "Low", "report_date": "2026-03-01"}'::JSONB),

('eh-doc-011', 'EQ-1200-D-003', 'rag-documents/equipment_health/EQ-1200-D-003.md',
'# Equipment Health Report: EQ-1200-D-003

## Overview
- **Equipment ID:** EQ-1200-D-003
- **Plant:** 1200 (Secondary Manufacturing)
- **Production Line:** LINE-D
- **Health Score:** 95.0 / 100
- **Failure Risk:** Low
- **Failure Probability:** 0.0256

## Sensor Summary
Excellent condition. All sensors nominal. Last maintenance 2026-01-30.

## Recommended Action
Continue routine monitoring. All parameters nominal.',
md5('EQ-1200-D-003-health'), 'equipment_health',
'{"equipment_id": "EQ-1200-D-003", "plant_code": "1200", "production_line": "LINE-D", "health_score": 95.0, "failure_risk": "Low", "report_date": "2026-03-01"}'::JSONB),

('eh-doc-012', 'EQ-2100-A-001', 'rag-documents/equipment_health/EQ-2100-A-001.md',
'# Equipment Health Report: EQ-2100-A-001

## Overview
- **Equipment ID:** EQ-2100-A-001
- **Plant:** 2100 (Assembly Plant 1)
- **Production Line:** LINE-A
- **Health Score:** 86.9 / 100
- **Failure Risk:** Low
- **Failure Probability:** 0.0745

## Sensor Summary
Temperature at 46.7 °C, vibration 2.4 mm/s, pressure 4.3 bar. All within normal operating ranges.

## Recommended Action
Routine inspection at next planned downtime.',
md5('EQ-2100-A-001-health'), 'equipment_health',
'{"equipment_id": "EQ-2100-A-001", "plant_code": "2100", "production_line": "LINE-A", "health_score": 86.9, "failure_risk": "Low", "report_date": "2026-03-01"}'::JSONB),

('eh-doc-013', 'EQ-2100-A-005', 'rag-documents/equipment_health/EQ-2100-A-005.md',
'# Equipment Health Report: EQ-2100-A-005

## Overview
- **Equipment ID:** EQ-2100-A-005
- **Plant:** 2100 (Assembly Plant 1)
- **Production Line:** LINE-A
- **Health Score:** 97.2 / 100
- **Failure Risk:** Low
- **Failure Probability:** 0.0134

## Sensor Summary
Top-performing equipment in the fleet. All sensors reading optimal. Vibration exceptionally low at 1.2 mm/s.

## Recommended Action
No action required. Equipment in excellent condition.',
md5('EQ-2100-A-005-health'), 'equipment_health',
'{"equipment_id": "EQ-2100-A-005", "plant_code": "2100", "production_line": "LINE-A", "health_score": 97.2, "failure_risk": "Low", "report_date": "2026-03-01"}'::JSONB),

('eh-doc-014', 'EQ-2100-B-003', 'rag-documents/equipment_health/EQ-2100-B-003.md',
'# Equipment Health Report: EQ-2100-B-003

## Overview
- **Equipment ID:** EQ-2100-B-003
- **Plant:** 2100 (Assembly Plant 1)
- **Production Line:** LINE-B
- **Health Score:** 82.4 / 100
- **Failure Risk:** Low
- **Failure Probability:** 0.0989

## Sensor Summary
Temperature at 48.3 °C (upper normal range). Vibration at 3.1 mm/s. 2 anomalies detected in last 30 days, both temperature-related.

## Recommended Action
Monitor closely. Schedule inspection if temperature continues to trend upward.',
md5('EQ-2100-B-003-health'), 'equipment_health',
'{"equipment_id": "EQ-2100-B-003", "plant_code": "2100", "production_line": "LINE-B", "health_score": 82.4, "failure_risk": "Low", "report_date": "2026-03-01"}'::JSONB),

('eh-doc-015', 'EQ-2100-C-002', 'rag-documents/equipment_health/EQ-2100-C-002.md',
'# Equipment Health Report: EQ-2100-C-002

## Overview
- **Equipment ID:** EQ-2100-C-002
- **Plant:** 2100 (Assembly Plant 1)
- **Production Line:** LINE-C
- **Health Score:** 91.8 / 100
- **Failure Risk:** Low

## Sensor Summary
Normal readings across all sensor types. Flow rate at 135.2 L/min. Power consumption at 4.5 kW.

## Recommended Action
Standard preventive maintenance per schedule.',
md5('EQ-2100-C-002-health'), 'equipment_health',
'{"equipment_id": "EQ-2100-C-002", "plant_code": "2100", "production_line": "LINE-C", "health_score": 91.8, "failure_risk": "Low", "report_date": "2026-03-01"}'::JSONB),

('eh-doc-016', 'EQ-2100-D-001', 'rag-documents/equipment_health/EQ-2100-D-001.md',
'# Equipment Health Report: EQ-2100-D-001

## Overview
- **Equipment ID:** EQ-2100-D-001
- **Plant:** 2100 (Assembly Plant 1)
- **Production Line:** LINE-D
- **Health Score:** 88.3 / 100
- **Failure Risk:** Low
- **Failure Probability:** 0.0634

## Sensor Summary
All sensors nominal. Humidity at 52.1 %RH, temperature 44.0 °C.

## Recommended Action
Continue routine monitoring.',
md5('EQ-2100-D-001-health'), 'equipment_health',
'{"equipment_id": "EQ-2100-D-001", "plant_code": "2100", "production_line": "LINE-D", "health_score": 88.3, "failure_risk": "Low", "report_date": "2026-03-01"}'::JSONB),

('eh-doc-017', 'EQ-2200-A-001', 'rag-documents/equipment_health/EQ-2200-A-001.md',
'# Equipment Health Report: EQ-2200-A-001

## Overview
- **Equipment ID:** EQ-2200-A-001
- **Plant:** 2200 (Assembly Plant 2)
- **Production Line:** LINE-A
- **Health Score:** 93.1 / 100
- **Failure Risk:** Low
- **Failure Probability:** 0.0378

## Sensor Summary
Excellent operating condition. Temperature 40.1 °C, vibration 1.5 mm/s. All readings well within normal bands.

## Recommended Action
No action required. Equipment operating within normal range.',
md5('EQ-2200-A-001-health'), 'equipment_health',
'{"equipment_id": "EQ-2200-A-001", "plant_code": "2200", "production_line": "LINE-A", "health_score": 93.1, "failure_risk": "Low", "report_date": "2026-03-01"}'::JSONB),

('eh-doc-018', 'EQ-2200-B-004', 'rag-documents/equipment_health/EQ-2200-B-004.md',
'# Equipment Health Report: EQ-2200-B-004

## Overview
- **Equipment ID:** EQ-2200-B-004
- **Plant:** 2200 (Assembly Plant 2)
- **Production Line:** LINE-B
- **Health Score:** 84.6 / 100
- **Failure Risk:** Low
- **Failure Probability:** 0.0867

## Sensor Summary
Pressure reading at 5.8 bar (upper normal range). Other sensors nominal. 1 uncertain reading on pressure sensor last week.

## Recommended Action
Review pressure sensor calibration at next maintenance window.',
md5('EQ-2200-B-004-health'), 'equipment_health',
'{"equipment_id": "EQ-2200-B-004", "plant_code": "2200", "production_line": "LINE-B", "health_score": 84.6, "failure_risk": "Low", "report_date": "2026-03-01"}'::JSONB),

('eh-doc-019', 'EQ-2200-C-003', 'rag-documents/equipment_health/EQ-2200-C-003.md',
'# Equipment Health Report: EQ-2200-C-003

## Overview
- **Equipment ID:** EQ-2200-C-003
- **Plant:** 2200 (Assembly Plant 2)
- **Production Line:** LINE-C
- **Health Score:** 90.0 / 100
- **Failure Risk:** Low

## Sensor Summary
All readings nominal. Equipment recently serviced on 2026-02-10.

## Recommended Action
Continue routine monitoring. All parameters nominal.',
md5('EQ-2200-C-003-health'), 'equipment_health',
'{"equipment_id": "EQ-2200-C-003", "plant_code": "2200", "production_line": "LINE-C", "health_score": 90.0, "failure_risk": "Low", "report_date": "2026-03-01"}'::JSONB),

('eh-doc-020', 'EQ-2200-D-002', 'rag-documents/equipment_health/EQ-2200-D-002.md',
'# Equipment Health Report: EQ-2200-D-002

## Overview
- **Equipment ID:** EQ-2200-D-002
- **Plant:** 2200 (Assembly Plant 2)
- **Production Line:** LINE-D
- **Health Score:** 86.5 / 100
- **Failure Risk:** Low

## Sensor Summary
Vibration slightly elevated at 3.0 mm/s (still within normal band of 1-4 mm/s). Power steady at 5.1 kW.

## Recommended Action
Schedule lubrication during next planned downtime.',
md5('EQ-2200-D-002-health'), 'equipment_health',
'{"equipment_id": "EQ-2200-D-002", "plant_code": "2200", "production_line": "LINE-D", "health_score": 86.5, "failure_risk": "Low", "report_date": "2026-03-01"}'::JSONB),

('eh-doc-021', 'EQ-1100-A-006', 'rag-documents/equipment_health/EQ-1100-A-006.md',
'# Equipment Health Report: EQ-1100-A-006

## Overview
- **Equipment ID:** EQ-1100-A-006
- **Plant:** 1100 (Primary Manufacturing)
- **Production Line:** LINE-A
- **Health Score:** 81.0 / 100
- **Failure Risk:** Low
- **Failure Probability:** 0.1045

## Sensor Summary
Temperature at 50.1 °C (approaching upper normal limit of 55 °C). Vibration at 3.4 mm/s. 2 anomalous readings in last 30 days.

## Recommended Action
Monitor closely. If temperature exceeds 55 °C, schedule immediate inspection.',
md5('EQ-1100-A-006-health'), 'equipment_health',
'{"equipment_id": "EQ-1100-A-006", "plant_code": "1100", "production_line": "LINE-A", "health_score": 81.0, "failure_risk": "Low", "report_date": "2026-03-01"}'::JSONB),

('eh-doc-022', 'EQ-1100-C-010', 'rag-documents/equipment_health/EQ-1100-C-010.md',
'# Equipment Health Report: EQ-1100-C-010

## Overview
- **Equipment ID:** EQ-1100-C-010
- **Plant:** 1100 (Primary Manufacturing)
- **Production Line:** LINE-C
- **Health Score:** 98.2 / 100
- **Failure Risk:** Low
- **Failure Probability:** 0.0089

## Sensor Summary
Best-in-class performance. All sensors at optimal levels. Recently overhauled in January 2026.

## Recommended Action
No action required. Continue standard monitoring schedule.',
md5('EQ-1100-C-010-health'), 'equipment_health',
'{"equipment_id": "EQ-1100-C-010", "plant_code": "1100", "production_line": "LINE-C", "health_score": 98.2, "failure_risk": "Low", "report_date": "2026-03-01"}'::JSONB),

('eh-doc-023', 'EQ-1200-B-007', 'rag-documents/equipment_health/EQ-1200-B-007.md',
'# Equipment Health Report: EQ-1200-B-007

## Overview
- **Equipment ID:** EQ-1200-B-007
- **Plant:** 1200 (Secondary Manufacturing)
- **Production Line:** LINE-B
- **Health Score:** 83.9 / 100
- **Failure Risk:** Low

## Sensor Summary
Humidity above average at 57.8 %RH. Temperature normal at 43.2 °C. Flow rate 118.4 L/min.

## Recommended Action
Check humidity sensor and environmental controls. Schedule filter replacement.',
md5('EQ-1200-B-007-health'), 'equipment_health',
'{"equipment_id": "EQ-1200-B-007", "plant_code": "1200", "production_line": "LINE-B", "health_score": 83.9, "failure_risk": "Low", "report_date": "2026-03-01"}'::JSONB),

('eh-doc-024', 'EQ-2100-D-008', 'rag-documents/equipment_health/EQ-2100-D-008.md',
'# Equipment Health Report: EQ-2100-D-008

## Overview
- **Equipment ID:** EQ-2100-D-008
- **Plant:** 2100 (Assembly Plant 1)
- **Production Line:** LINE-D
- **Health Score:** 87.6 / 100
- **Failure Risk:** Low

## Sensor Summary
All sensors nominal. Steady-state operation. Power consumption at 3.7 kW, well within range.

## Recommended Action
Continue routine monitoring. Next preventive maintenance in 4 months.',
md5('EQ-2100-D-008-health'), 'equipment_health',
'{"equipment_id": "EQ-2100-D-008", "plant_code": "2100", "production_line": "LINE-D", "health_score": 87.6, "failure_risk": "Low", "report_date": "2026-03-01"}'::JSONB),

('eh-doc-025', 'EQ-2200-A-009', 'rag-documents/equipment_health/EQ-2200-A-009.md',
'# Equipment Health Report: EQ-2200-A-009

## Overview
- **Equipment ID:** EQ-2200-A-009
- **Plant:** 2200 (Assembly Plant 2)
- **Production Line:** LINE-A
- **Health Score:** 91.7 / 100
- **Failure Risk:** Low

## Sensor Summary
All readings within normal bands. Temperature 39.8 °C, pressure 4.9 bar.

## Recommended Action
Standard preventive maintenance per schedule.',
md5('EQ-2200-A-009-health'), 'equipment_health',
'{"equipment_id": "EQ-2200-A-009", "plant_code": "2200", "production_line": "LINE-A", "health_score": 91.7, "failure_risk": "Low", "report_date": "2026-03-01"}'::JSONB),

('eh-doc-026', 'EQ-1100-D-011', 'rag-documents/equipment_health/EQ-1100-D-011.md',
'# Equipment Health Report: EQ-1100-D-011

## Overview
- **Equipment ID:** EQ-1100-D-011
- **Plant:** 1100 (Primary Manufacturing)
- **Production Line:** LINE-D
- **Health Score:** 95.4 / 100
- **Failure Risk:** Low

## Sensor Summary
Excellent condition. Vibration at 1.3 mm/s (very low). All other sensors nominal.

## Recommended Action
Continue routine monitoring. All parameters nominal.',
md5('EQ-1100-D-011-health'), 'equipment_health',
'{"equipment_id": "EQ-1100-D-011", "plant_code": "1100", "production_line": "LINE-D", "health_score": 95.4, "failure_risk": "Low", "report_date": "2026-03-01"}'::JSONB),

('eh-doc-027', 'EQ-1200-C-006', 'rag-documents/equipment_health/EQ-1200-C-006.md',
'# Equipment Health Report: EQ-1200-C-006

## Overview
- **Equipment ID:** EQ-1200-C-006
- **Plant:** 1200 (Secondary Manufacturing)
- **Production Line:** LINE-C
- **Health Score:** 89.1 / 100
- **Failure Risk:** Low

## Sensor Summary
All readings normal. Minor fluctuation in flow rate (ranging 110-145 L/min) but within acceptable limits.

## Recommended Action
Routine inspection at next planned downtime.',
md5('EQ-1200-C-006-health'), 'equipment_health',
'{"equipment_id": "EQ-1200-C-006", "plant_code": "1200", "production_line": "LINE-C", "health_score": 89.1, "failure_risk": "Low", "report_date": "2026-03-01"}'::JSONB),

('eh-doc-028', 'EQ-2100-B-010', 'rag-documents/equipment_health/EQ-2100-B-010.md',
'# Equipment Health Report: EQ-2100-B-010

## Overview
- **Equipment ID:** EQ-2100-B-010
- **Plant:** 2100 (Assembly Plant 1)
- **Production Line:** LINE-B
- **Health Score:** 94.0 / 100
- **Failure Risk:** Low

## Sensor Summary
Operating at peak efficiency. Temperature 41.2 °C, vibration 1.7 mm/s, power 2.8 kW.

## Recommended Action
No action required. Equipment operating within normal range.',
md5('EQ-2100-B-010-health'), 'equipment_health',
'{"equipment_id": "EQ-2100-B-010", "plant_code": "2100", "production_line": "LINE-B", "health_score": 94.0, "failure_risk": "Low", "report_date": "2026-03-01"}'::JSONB),

('eh-doc-029', 'EQ-2200-C-012', 'rag-documents/equipment_health/EQ-2200-C-012.md',
'# Equipment Health Report: EQ-2200-C-012

## Overview
- **Equipment ID:** EQ-2200-C-012
- **Plant:** 2200 (Assembly Plant 2)
- **Production Line:** LINE-C
- **Health Score:** 80.5 / 100
- **Failure Risk:** Low

## Sensor Summary
Borderline readings on temperature (53.8 °C) and vibration (3.8 mm/s). Both still within normal range but near upper limits.

## Recommended Action
Schedule inspection within next 30 days. Monitor temperature and vibration trends.',
md5('EQ-2200-C-012-health'), 'equipment_health',
'{"equipment_id": "EQ-2200-C-012", "plant_code": "2200", "production_line": "LINE-C", "health_score": 80.5, "failure_risk": "Low", "report_date": "2026-03-01"}'::JSONB),

('eh-doc-030', 'EQ-1200-D-013', 'rag-documents/equipment_health/EQ-1200-D-013.md',
'# Equipment Health Report: EQ-1200-D-013

## Overview
- **Equipment ID:** EQ-1200-D-013
- **Plant:** 1200 (Secondary Manufacturing)
- **Production Line:** LINE-D
- **Health Score:** 92.3 / 100
- **Failure Risk:** Low

## Sensor Summary
All sensors reading within normal operating ranges. Equipment recently calibrated.

## Recommended Action
Continue routine monitoring.',
md5('EQ-1200-D-013-health'), 'equipment_health',
'{"equipment_id": "EQ-1200-D-013", "plant_code": "1200", "production_line": "LINE-D", "health_score": 92.3, "failure_risk": "Low", "report_date": "2026-03-01"}'::JSONB),

('eh-doc-031', 'EQ-2200-D-007', 'rag-documents/equipment_health/EQ-2200-D-007.md',
'# Equipment Health Report: EQ-2200-D-007

## Overview
- **Equipment ID:** EQ-2200-D-007
- **Plant:** 2200 (Assembly Plant 2)
- **Production Line:** LINE-D
- **Health Score:** 85.8 / 100
- **Failure Risk:** Low

## Sensor Summary
All sensors within normal ranges. Power consumption at 6.2 kW (moderate). Humidity at 47.3 %RH.

## Recommended Action
Standard preventive maintenance per schedule.',
md5('EQ-2200-D-007-health'), 'equipment_health',
'{"equipment_id": "EQ-2200-D-007", "plant_code": "2200", "production_line": "LINE-D", "health_score": 85.8, "failure_risk": "Low", "report_date": "2026-03-01"}'::JSONB),

('eh-doc-032', 'EQ-1100-B-009', 'rag-documents/equipment_health/EQ-1100-B-009.md',
'# Equipment Health Report: EQ-1100-B-009

## Overview
- **Equipment ID:** EQ-1100-B-009
- **Plant:** 1100 (Primary Manufacturing)
- **Production Line:** LINE-B
- **Health Score:** 96.7 / 100
- **Failure Risk:** Low

## Sensor Summary
Excellent operating condition across all sensors. Recently maintained. Vibration at 1.1 mm/s (lowest on LINE-B).

## Recommended Action
No action required. Continue routine monitoring schedule.',
md5('EQ-1100-B-009-health'), 'equipment_health',
'{"equipment_id": "EQ-1100-B-009", "plant_code": "1100", "production_line": "LINE-B", "health_score": 96.7, "failure_risk": "Low", "report_date": "2026-03-01"}'::JSONB),

('eh-doc-033', 'EQ-2100-C-004', 'rag-documents/equipment_health/EQ-2100-C-004.md',
'# Equipment Health Report: EQ-2100-C-004

## Overview
- **Equipment ID:** EQ-2100-C-004
- **Plant:** 2100 (Assembly Plant 1)
- **Production Line:** LINE-C
- **Health Score:** 88.0 / 100
- **Failure Risk:** Low

## Sensor Summary
Temperature 45.6 °C, vibration 2.6 mm/s, pressure 4.1 bar. All nominal.

## Recommended Action
Continue routine monitoring.',
md5('EQ-2100-C-004-health'), 'equipment_health',
'{"equipment_id": "EQ-2100-C-004", "plant_code": "2100", "production_line": "LINE-C", "health_score": 88.0, "failure_risk": "Low", "report_date": "2026-03-01"}'::JSONB),

('eh-doc-034', 'EQ-1100-A-012', 'rag-documents/equipment_health/EQ-1100-A-012.md',
'# Equipment Health Report: EQ-1100-A-012

## Overview
- **Equipment ID:** EQ-1100-A-012
- **Plant:** 1100 (Primary Manufacturing)
- **Production Line:** LINE-A
- **Health Score:** 83.2 / 100
- **Failure Risk:** Low
- **Failure Probability:** 0.0945

## Sensor Summary
Slightly elevated vibration at 3.5 mm/s. Temperature normal at 47.0 °C. No anomalies in last 30 days.

## Recommended Action
Monitor vibration trend. Plan lubrication at next maintenance window.',
md5('EQ-1100-A-012-health'), 'equipment_health',
'{"equipment_id": "EQ-1100-A-012", "plant_code": "1100", "production_line": "LINE-A", "health_score": 83.2, "failure_risk": "Low", "report_date": "2026-03-01"}'::JSONB),

('eh-doc-035', 'EQ-2200-B-011', 'rag-documents/equipment_health/EQ-2200-B-011.md',
'# Equipment Health Report: EQ-2200-B-011

## Overview
- **Equipment ID:** EQ-2200-B-011
- **Plant:** 2200 (Assembly Plant 2)
- **Production Line:** LINE-B
- **Health Score:** 90.8 / 100
- **Failure Risk:** Low

## Sensor Summary
All readings within normal parameters. Equipment performing well.

## Recommended Action
Continue routine monitoring. All parameters nominal.',
md5('EQ-2200-B-011-health'), 'equipment_health',
'{"equipment_id": "EQ-2200-B-011", "plant_code": "2200", "production_line": "LINE-B", "health_score": 90.8, "failure_risk": "Low", "report_date": "2026-03-01"}'::JSONB),


-- ===== Medium Risk Equipment (8 documents) =====

('eh-doc-036', 'EQ-1100-A-003', 'rag-documents/equipment_health/EQ-1100-A-003.md',
'# Equipment Health Report: EQ-1100-A-003

## Overview
- **Equipment ID:** EQ-1100-A-003
- **Plant:** 1100 (Primary Manufacturing)
- **Production Line:** LINE-A
- **Health Score:** 67.4 / 100
- **Failure Risk:** Medium
- **Failure Probability:** 0.2345
- **Estimated Remaining Useful Life:** 95 days

## Sensor Summary
| Sensor | Value | Status |
|--------|-------|--------|
| Temperature | 52.8 °C | ELEVATED |
| Vibration | 3.7 mm/s | ELEVATED |
| Pressure | 5.1 bar | NORMAL |
| Humidity | 54.3 %RH | NORMAL |
| Flow Rate | 108.2 L/min | NORMAL |
| Power | 6.8 kW | ELEVATED |

## Anomalies (Last 30 Days)
4 anomalies detected:
- 2x temperature exceedance (> 55 °C, brief spikes)
- 1x vibration spike (4.8 mm/s, lasted 20 minutes)
- 1x power surge (8.2 kW)

## Risk Factors
- minor_vibration_increase
- humidity_fluctuation
- temperature_trending_up

## Recommended Action
Monitor closely. Schedule inspection within 2 weeks. Review vibration trend and consider bearing assessment.',
md5('EQ-1100-A-003-health'), 'equipment_health',
'{"equipment_id": "EQ-1100-A-003", "plant_code": "1100", "production_line": "LINE-A", "health_score": 67.4, "failure_risk": "Medium", "report_date": "2026-03-01"}'::JSONB),

('eh-doc-037', 'EQ-1200-C-008', 'rag-documents/equipment_health/EQ-1200-C-008.md',
'# Equipment Health Report: EQ-1200-C-008

## Overview
- **Equipment ID:** EQ-1200-C-008
- **Plant:** 1200 (Secondary Manufacturing)
- **Production Line:** LINE-C
- **Health Score:** 71.2 / 100
- **Failure Risk:** Medium
- **Failure Probability:** 0.2012
- **Estimated Remaining Useful Life:** 112 days

## Sensor Summary
Vibration consistently above 3.5 mm/s over the past week. Temperature at 51.4 °C. 3 anomalous readings in last 30 days.

## Risk Factors
- vibration_trend_increasing
- temperature_approaching_warning_threshold

## Recommended Action
Schedule lubrication and bearing inspection within 2 weeks. Review sensor calibration.',
md5('EQ-1200-C-008-health'), 'equipment_health',
'{"equipment_id": "EQ-1200-C-008", "plant_code": "1200", "production_line": "LINE-C", "health_score": 71.2, "failure_risk": "Medium", "report_date": "2026-03-01"}'::JSONB),

('eh-doc-038', 'EQ-2100-A-007', 'rag-documents/equipment_health/EQ-2100-A-007.md',
'# Equipment Health Report: EQ-2100-A-007

## Overview
- **Equipment ID:** EQ-2100-A-007
- **Plant:** 2100 (Assembly Plant 1)
- **Production Line:** LINE-A
- **Health Score:** 64.8 / 100
- **Failure Risk:** Medium
- **Failure Probability:** 0.2567
- **Estimated Remaining Useful Life:** 78 days

## Sensor Summary
Temperature at 54.1 °C (near warning threshold of 60 °C). Vibration at 3.9 mm/s. Power consumption trending up (7.3 kW). 5 anomalies in last 30 days.

## Risk Factors
- temperature_approaching_warning
- vibration_elevated
- power_consumption_trend

## Recommended Action
Schedule inspection immediately. Plan filter replacement and cooling system review within 1 week.',
md5('EQ-2100-A-007-health'), 'equipment_health',
'{"equipment_id": "EQ-2100-A-007", "plant_code": "2100", "production_line": "LINE-A", "health_score": 64.8, "failure_risk": "Medium", "report_date": "2026-03-01"}'::JSONB),

('eh-doc-039', 'EQ-2200-B-006', 'rag-documents/equipment_health/EQ-2200-B-006.md',
'# Equipment Health Report: EQ-2200-B-006

## Overview
- **Equipment ID:** EQ-2200-B-006
- **Plant:** 2200 (Assembly Plant 2)
- **Production Line:** LINE-B
- **Health Score:** 73.5 / 100
- **Failure Risk:** Medium
- **Failure Probability:** 0.1856
- **Estimated Remaining Useful Life:** 130 days

## Sensor Summary
Humidity readings inconsistent (ranging 38-65 %RH). Pressure fluctuating between 3.8-5.9 bar. 3 uncertain quality readings last month.

## Recommended Action
Review sensor calibration. Schedule inspection during next planned downtime. Plan filter replacement.',
md5('EQ-2200-B-006-health'), 'equipment_health',
'{"equipment_id": "EQ-2200-B-006", "plant_code": "2200", "production_line": "LINE-B", "health_score": 73.5, "failure_risk": "Medium", "report_date": "2026-03-01"}'::JSONB),

('eh-doc-040', 'EQ-1100-D-004', 'rag-documents/equipment_health/EQ-1100-D-004.md',
'# Equipment Health Report: EQ-1100-D-004

## Overview
- **Equipment ID:** EQ-1100-D-004
- **Plant:** 1100 (Primary Manufacturing)
- **Production Line:** LINE-D
- **Health Score:** 68.9 / 100
- **Failure Risk:** Medium
- **Failure Probability:** 0.2189
- **Estimated Remaining Useful Life:** 88 days

## Sensor Summary
Power consumption elevated (7.8 kW). Vibration at 3.6 mm/s. Flow rate reduced to 95 L/min (below typical 110+).

## Risk Factors
- power_consumption_anomaly
- flow_rate_declining
- vibration_increasing

## Recommended Action
Schedule urgent maintenance within 2 weeks. Investigate drive belt condition and motor alignment.',
md5('EQ-1100-D-004-health'), 'equipment_health',
'{"equipment_id": "EQ-1100-D-004", "plant_code": "1100", "production_line": "LINE-D", "health_score": 68.9, "failure_risk": "Medium", "report_date": "2026-03-01"}'::JSONB),

('eh-doc-041', 'EQ-1200-A-010', 'rag-documents/equipment_health/EQ-1200-A-010.md',
'# Equipment Health Report: EQ-1200-A-010

## Overview
- **Equipment ID:** EQ-1200-A-010
- **Plant:** 1200 (Secondary Manufacturing)
- **Production Line:** LINE-A
- **Health Score:** 62.1 / 100
- **Failure Risk:** Medium
- **Failure Probability:** 0.2734
- **Estimated Remaining Useful Life:** 68 days

## Sensor Summary
Multiple sensor readings trending toward warning thresholds. Temperature 53.7 °C, vibration 3.8 mm/s. 6 anomalies in 30 days.

## Recommended Action
Plan bearing replacement. Schedule cooling system inspection within 10 days.',
md5('EQ-1200-A-010-health'), 'equipment_health',
'{"equipment_id": "EQ-1200-A-010", "plant_code": "1200", "production_line": "LINE-A", "health_score": 62.1, "failure_risk": "Medium", "report_date": "2026-03-01"}'::JSONB),

('eh-doc-042', 'EQ-2100-C-011', 'rag-documents/equipment_health/EQ-2100-C-011.md',
'# Equipment Health Report: EQ-2100-C-011

## Overview
- **Equipment ID:** EQ-2100-C-011
- **Plant:** 2100 (Assembly Plant 1)
- **Production Line:** LINE-C
- **Health Score:** 76.3 / 100
- **Failure Risk:** Medium
- **Failure Probability:** 0.1645

## Sensor Summary
Occasional pressure drops to 3.2 bar (approaching warning threshold of 3 bar). Other sensors nominal.

## Recommended Action
Inspect pressure regulation system. Monitor closely over next 2 weeks.',
md5('EQ-2100-C-011-health'), 'equipment_health',
'{"equipment_id": "EQ-2100-C-011", "plant_code": "2100", "production_line": "LINE-C", "health_score": 76.3, "failure_risk": "Medium", "report_date": "2026-03-01"}'::JSONB),

('eh-doc-043', 'EQ-2200-D-005', 'rag-documents/equipment_health/EQ-2200-D-005.md',
'# Equipment Health Report: EQ-2200-D-005

## Overview
- **Equipment ID:** EQ-2200-D-005
- **Plant:** 2200 (Assembly Plant 2)
- **Production Line:** LINE-D
- **Health Score:** 69.7 / 100
- **Failure Risk:** Medium
- **Failure Probability:** 0.2098

## Sensor Summary
Vibration at 3.7 mm/s (approaching upper normal limit). Temperature 50.5 °C. 4 anomalies in last 30 days.

## Recommended Action
Schedule maintenance within 2 weeks. Bearing assessment recommended.',
md5('EQ-2200-D-005-health'), 'equipment_health',
'{"equipment_id": "EQ-2200-D-005", "plant_code": "2200", "production_line": "LINE-D", "health_score": 69.7, "failure_risk": "Medium", "report_date": "2026-03-01"}'::JSONB),


-- ===== High Risk Equipment (2 documents) =====

('eh-doc-044', 'EQ-1100-C-007', 'rag-documents/equipment_health/EQ-1100-C-007.md',
'# Equipment Health Report: EQ-1100-C-007

## Overview
- **Equipment ID:** EQ-1100-C-007
- **Plant:** 1100 (Primary Manufacturing)
- **Production Line:** LINE-C
- **Health Score:** 38.2 / 100
- **Failure Risk:** High
- **Failure Probability:** 0.5123
- **Estimated Remaining Useful Life:** 28 days

## Sensor Summary
| Sensor | Value | Status |
|--------|-------|--------|
| Temperature | 62.3 °C | **WARNING** |
| Vibration | 5.8 mm/s | **WARNING** |
| Pressure | 3.1 bar | WARNING (low) |
| Humidity | 67.4 %RH | ELEVATED |
| Flow Rate | 72.1 L/min | LOW |
| Power | 8.9 kW | **HIGH** |

## Anomalies (Last 30 Days)
12 anomalies detected:
- 5x temperature exceedance (> 60 °C sustained)
- 4x vibration warning (> 5 mm/s)
- 2x power consumption spike (> 9 kW)
- 1x flow rate drop (< 70 L/min)

## Risk Factors
- high_vibration_trend
- temperature_exceedance
- bearing_wear_indicator
- power_consumption_anomaly

## Lifecycle History
- Last maintenance: 2025-09-15
- State: DEGRADING since 2026-01-20
- Transitioned from WARNING to HIGH RISK on 2026-02-15

## Recommended Action
**URGENT:** Schedule bearing replacement within 1 week. Cooling system requires inspection. Reduce production load on LINE-C until maintenance is completed. Consider temporary redistribution to LINE-A or LINE-B.',
md5('EQ-1100-C-007-health'), 'equipment_health',
'{"equipment_id": "EQ-1100-C-007", "plant_code": "1100", "production_line": "LINE-C", "health_score": 38.2, "failure_risk": "High", "report_date": "2026-03-01"}'::JSONB),

('eh-doc-045', 'EQ-2100-B-009', 'rag-documents/equipment_health/EQ-2100-B-009.md',
'# Equipment Health Report: EQ-2100-B-009

## Overview
- **Equipment ID:** EQ-2100-B-009
- **Plant:** 2100 (Assembly Plant 1)
- **Production Line:** LINE-B
- **Health Score:** 42.7 / 100
- **Failure Risk:** High
- **Failure Probability:** 0.4678
- **Estimated Remaining Useful Life:** 35 days

## Sensor Summary
Temperature at 59.8 °C (near critical threshold). Vibration sustained above 5 mm/s (5.4 mm/s). Power consumption elevated at 8.5 kW. 10 anomalies in last 30 days.

## Risk Factors
- high_vibration_trend
- temperature_exceedance
- power_consumption_anomaly
- bearing_wear_indicator

## Recommended Action
**URGENT:** Plan maintenance within 2 weeks. Vibration analysis indicates probable bearing wear. Schedule replacement and motor inspection. Monitor daily until maintenance is performed.',
md5('EQ-2100-B-009-health'), 'equipment_health',
'{"equipment_id": "EQ-2100-B-009", "plant_code": "2100", "production_line": "LINE-B", "health_score": 42.7, "failure_risk": "High", "report_date": "2026-03-01"}'::JSONB),


-- ===== Critical Risk Equipment (3 documents) =====

('eh-doc-046', 'EQ-1200-B-005', 'rag-documents/equipment_health/EQ-1200-B-005.md',
'# Equipment Health Report: EQ-1200-B-005

## Overview
- **Equipment ID:** EQ-1200-B-005
- **Plant:** 1200 (Secondary Manufacturing)
- **Production Line:** LINE-B
- **Health Score:** 15.3 / 100
- **Failure Risk:** Critical
- **Failure Probability:** 0.8912
- **Estimated Remaining Useful Life:** 5 days

## Sensor Summary
| Sensor | Value | Status |
|--------|-------|--------|
| Temperature | 71.2 °C | **CRITICAL** |
| Vibration | 7.8 mm/s | **CRITICAL** |
| Pressure | 2.1 bar | **CRITICAL (low)** |
| Humidity | 78.3 %RH | WARNING |
| Flow Rate | 38.4 L/min | **CRITICAL (low)** |
| Power | 9.7 kW | **CRITICAL** |

## Anomalies (Last 30 Days)
28 anomalies detected. Equipment in continuous degradation since 2026-01-10. Multiple sensor alarms daily.

## Risk Factors
- high_vibration_trend
- temperature_exceedance
- bearing_wear_indicator
- power_consumption_anomaly
- coolant_system_failure
- seal_degradation

## Lifecycle History
- HEALTHY -> DEGRADING (2025-11-05)
- DEGRADING -> WARNING (2025-12-20)
- WARNING -> CRITICAL (2026-01-10)
- Multiple maintenance attempts have not resolved root cause

## Recommended Action
**EMERGENCY:** Immediate shutdown and comprehensive inspection required. Bearing assembly likely failed. Coolant system seal breach suspected. Do not operate until maintenance team has completed full assessment. Human verification required before returning to service.',
md5('EQ-1200-B-005-health'), 'equipment_health',
'{"equipment_id": "EQ-1200-B-005", "plant_code": "1200", "production_line": "LINE-B", "health_score": 15.3, "failure_risk": "Critical", "report_date": "2026-03-01"}'::JSONB),

('eh-doc-047', 'EQ-2200-A-013', 'rag-documents/equipment_health/EQ-2200-A-013.md',
'# Equipment Health Report: EQ-2200-A-013

## Overview
- **Equipment ID:** EQ-2200-A-013
- **Plant:** 2200 (Assembly Plant 2)
- **Production Line:** LINE-A
- **Health Score:** 12.8 / 100
- **Failure Risk:** Critical
- **Failure Probability:** 0.9234
- **Estimated Remaining Useful Life:** 3 days

## Sensor Summary
All sensors in critical range. Temperature 73.5 °C (exceeded critical threshold of 70 °C). Vibration 8.2 mm/s (exceeded critical threshold of 7 mm/s). Equipment exhibiting failure mode behavior.

## Anomalies (Last 30 Days)
35 anomalies. Continuous alarm state since 2026-02-20.

## Recommended Action
**EMERGENCY:** Shut down immediately. Do not operate. Motor replacement required. Schedule comprehensive overhaul. Estimated downtime: 3-5 days. Human verification required.',
md5('EQ-2200-A-013-health'), 'equipment_health',
'{"equipment_id": "EQ-2200-A-013", "plant_code": "2200", "production_line": "LINE-A", "health_score": 12.8, "failure_risk": "Critical", "report_date": "2026-03-01"}'::JSONB),

('eh-doc-048', 'EQ-1100-B-013', 'rag-documents/equipment_health/EQ-1100-B-013.md',
'# Equipment Health Report: EQ-1100-B-013

## Overview
- **Equipment ID:** EQ-1100-B-013
- **Plant:** 1100 (Primary Manufacturing)
- **Production Line:** LINE-B
- **Health Score:** 8.5 / 100
- **Failure Risk:** Critical
- **Failure Probability:** 0.9567
- **Estimated Remaining Useful Life:** 1 day

## Sensor Summary
Equipment has effectively failed. Temperature 78.1 °C (CRITICAL). Vibration 9.1 mm/s (CRITICAL). Power draw erratic. Pressure collapsed to 1.8 bar.

## Anomalies (Last 30 Days)
42 anomalies. Equipment transitioned to FAILED state on 2026-03-01.

## Lifecycle History
- HEALTHY -> DEGRADING (2025-10-15)
- DEGRADING -> WARNING (2025-12-01)
- WARNING -> CRITICAL (2026-02-01)
- CRITICAL -> FAILED (2026-03-01)

## Recommended Action
**EMERGENCY:** Equipment has FAILED. Isolate immediately. Full replacement of motor assembly, bearing unit, and cooling system required. Production on LINE-B must be redistributed. Incident report required per safety protocol.',
md5('EQ-1100-B-013-health'), 'equipment_health',
'{"equipment_id": "EQ-1100-B-013", "plant_code": "1100", "production_line": "LINE-B", "health_score": 8.5, "failure_risk": "Critical", "report_date": "2026-03-01"}'::JSONB),


-- ===== Maintenance Guide Documents (2 documents) =====

('eh-doc-049', 'maintenance-guide-bearings', 'rag-documents/equipment_health/maintenance-guide-bearings.md',
'# Bearing Maintenance Guide

## Overview
Bearing failures account for approximately 40% of all equipment failures in manufacturing plants. Early detection through vibration analysis is the primary prevention method.

## Symptoms of Bearing Degradation
1. **Vibration increase:** Gradual rise from baseline (normal: 1-4 mm/s, warning: > 5 mm/s, critical: > 7 mm/s)
2. **Temperature increase:** Bearing friction generates heat. Monitor for sustained readings above normal baseline.
3. **Noise changes:** Audible grinding, clicking, or rumbling during operation.
4. **Power consumption increase:** Motor works harder to overcome bearing friction.

## Preventive Actions
- **Lubrication schedule:** Every 3 months for standard equipment, monthly for high-utilization machines
- **Vibration monitoring:** Weekly readings; daily monitoring for equipment with health score below 70
- **Temperature trending:** Flag any equipment with temperature > 55 °C for bearing inspection
- **Replacement threshold:** Replace bearings when vibration consistently exceeds 5 mm/s or estimated RUL < 30 days

## Emergency Procedures
For equipment with health score < 20 or vibration > 7 mm/s:
1. Initiate controlled shutdown
2. Isolate equipment from production line
3. Notify maintenance supervisor and plant manager
4. Do not restart without maintenance team clearance
5. File incident report per safety protocol',
md5('maintenance-guide-bearings'), 'equipment_health',
'{"document_type": "maintenance_guide", "topic": "bearing_maintenance", "applicable_equipment_types": ["all"], "report_date": "2026-03-01"}'::JSONB),

('eh-doc-050', 'maintenance-guide-cooling', 'rag-documents/equipment_health/maintenance-guide-cooling.md',
'# Cooling System Maintenance Guide

## Overview
Cooling system failures lead to thermal runaway, which is the second most common cause of unplanned downtime. Proactive monitoring of temperature and flow rate sensors is essential.

## Normal Operating Parameters
- **Coolant temperature:** 35-55 °C (warning at 60 °C, critical at 70 °C)
- **Flow rate:** 100-200 L/min (warning below 80 L/min, critical below 50 L/min)
- **Pressure:** 4-6 bar (warning outside 3-8 bar range)

## Common Failure Modes
1. **Seal degradation:** Causes coolant leaks, leading to reduced flow rate and rising temperatures
2. **Pump wear:** Results in reduced flow rate and pressure fluctuations
3. **Clogged filters:** Restricts flow, increases pressure differential
4. **Thermostat failure:** Equipment cannot regulate temperature effectively

## Preventive Maintenance Schedule
- **Filter replacement:** Every 6 months or when pressure differential exceeds 1.5 bar
- **Seal inspection:** Every 3 months; replace immediately if any wear detected
- **Coolant level check:** Weekly
- **Full system flush:** Annually

## When to Escalate
Escalate to maintenance supervisor when:
- Temperature exceeds 60 °C for more than 30 minutes
- Flow rate drops below 80 L/min
- Multiple temperature anomalies (> 3) in a 7-day period
- Equipment health score drops below 60 with temperature as a risk factor',
md5('maintenance-guide-cooling'), 'equipment_health',
'{"document_type": "maintenance_guide", "topic": "cooling_system_maintenance", "applicable_equipment_types": ["all"], "report_date": "2026-03-01"}'::JSONB);


-- ---------------------------------------------------------------------------
-- 5. Search Functions (from setup_pgvector.sql)
-- ---------------------------------------------------------------------------

-- Function: Semantic search on document_embeddings
CREATE OR REPLACE FUNCTION search_documents_semantic(
    query_embedding vector(1536),
    match_count INTEGER DEFAULT 5,
    min_similarity FLOAT DEFAULT 0.3,
    document_type_filter TEXT DEFAULT NULL,
    metadata_filter JSONB DEFAULT NULL
)
RETURNS TABLE (
    id TEXT,
    document_id TEXT,
    content TEXT,
    document_type TEXT,
    metadata JSONB,
    source_file TEXT,
    similarity FLOAT
)
LANGUAGE plpgsql
AS $$
BEGIN
    RETURN QUERY
    SELECT
        de.id,
        de.document_id,
        de.content,
        de.document_type,
        de.metadata,
        de.source_file,
        (1 - (de.embedding <=> query_embedding))::FLOAT AS similarity
    FROM document_embeddings de
    WHERE
        (document_type_filter IS NULL OR de.document_type = document_type_filter)
        AND (metadata_filter IS NULL OR de.metadata @> metadata_filter)
        AND (1 - (de.embedding <=> query_embedding)) >= min_similarity
    ORDER BY de.embedding <=> query_embedding
    LIMIT match_count;
END;
$$;

COMMENT ON FUNCTION search_documents_semantic IS
    'Semantic search on document_embeddings with optional document_type filter.';


-- Function: Full-text keyword search on document_embeddings
CREATE OR REPLACE FUNCTION search_documents_keyword(
    search_query TEXT,
    match_count INTEGER DEFAULT 5,
    document_type_filter TEXT DEFAULT NULL,
    metadata_filter JSONB DEFAULT NULL
)
RETURNS TABLE (
    id TEXT,
    document_id TEXT,
    content TEXT,
    document_type TEXT,
    metadata JSONB,
    source_file TEXT,
    rank_score FLOAT
)
LANGUAGE plpgsql
AS $$
DECLARE
    tsquery_val tsquery;
BEGIN
    tsquery_val := plainto_tsquery('english', search_query);

    RETURN QUERY
    SELECT
        de.id,
        de.document_id,
        de.content,
        de.document_type,
        de.metadata,
        de.source_file,
        ts_rank_cd(de.content_tsv, tsquery_val)::FLOAT AS rank_score
    FROM document_embeddings de
    WHERE
        de.content_tsv @@ tsquery_val
        AND (document_type_filter IS NULL OR de.document_type = document_type_filter)
        AND (metadata_filter IS NULL OR de.metadata @> metadata_filter)
    ORDER BY rank_score DESC
    LIMIT match_count;
END;
$$;

COMMENT ON FUNCTION search_documents_keyword IS
    'Full-text keyword search on document_embeddings with optional document_type filter.';


-- Function: Hybrid search on document_embeddings with RRF
CREATE OR REPLACE FUNCTION search_documents_hybrid(
    query_embedding vector(1536),
    search_query TEXT,
    match_count INTEGER DEFAULT 5,
    semantic_weight FLOAT DEFAULT 0.7,
    keyword_weight FLOAT DEFAULT 0.3,
    rrf_k INTEGER DEFAULT 60,
    document_type_filter TEXT DEFAULT NULL,
    metadata_filter JSONB DEFAULT NULL
)
RETURNS TABLE (
    id TEXT,
    document_id TEXT,
    content TEXT,
    document_type TEXT,
    metadata JSONB,
    source_file TEXT,
    semantic_score FLOAT,
    keyword_score FLOAT,
    combined_score FLOAT
)
LANGUAGE plpgsql
AS $$
BEGIN
    RETURN QUERY
    WITH semantic_results AS (
        SELECT
            s.id,
            s.document_id,
            s.content,
            s.document_type,
            s.metadata,
            s.source_file,
            s.similarity AS sem_score,
            ROW_NUMBER() OVER (ORDER BY s.similarity DESC) AS sem_rank
        FROM search_documents_semantic(
            query_embedding, match_count * 3, 0.1, document_type_filter, metadata_filter
        ) s
    ),
    keyword_results AS (
        SELECT
            k.id,
            k.document_id,
            k.content,
            k.document_type,
            k.metadata,
            k.source_file,
            k.rank_score AS kw_score,
            ROW_NUMBER() OVER (ORDER BY k.rank_score DESC) AS kw_rank
        FROM search_documents_keyword(
            search_query, match_count * 3, document_type_filter, metadata_filter
        ) k
    ),
    combined AS (
        SELECT
            COALESCE(s.id, k.id) AS id,
            COALESCE(s.document_id, k.document_id) AS document_id,
            COALESCE(s.content, k.content) AS content,
            COALESCE(s.document_type, k.document_type) AS document_type,
            COALESCE(s.metadata, k.metadata) AS metadata,
            COALESCE(s.source_file, k.source_file) AS source_file,
            COALESCE(s.sem_score, 0)::FLOAT AS semantic_score,
            COALESCE(k.kw_score, 0)::FLOAT AS keyword_score,
            (
                COALESCE(semantic_weight / (rrf_k + s.sem_rank), 0) +
                COALESCE(keyword_weight / (rrf_k + k.kw_rank), 0)
            )::FLOAT AS combined_score
        FROM semantic_results s
        FULL OUTER JOIN keyword_results k ON s.id = k.id
    )
    SELECT
        c.id,
        c.document_id,
        c.content,
        c.document_type,
        c.metadata,
        c.source_file,
        c.semantic_score,
        c.keyword_score,
        c.combined_score
    FROM combined c
    ORDER BY c.combined_score DESC
    LIMIT match_count;
END;
$$;

COMMENT ON FUNCTION search_documents_hybrid IS
    'Hybrid search on document_embeddings combining semantic and keyword search '
    'with RRF scoring. Filter by document_type (e.g., equipment_health, customer_360).';


-- ---------------------------------------------------------------------------
-- 6. Verify Setup
-- ---------------------------------------------------------------------------
DO $$
DECLARE
    doc_count   BIGINT;
    func_count  INTEGER;
    index_count INTEGER;
BEGIN
    SELECT COUNT(*) INTO doc_count FROM document_embeddings;

    SELECT COUNT(*) INTO func_count
    FROM information_schema.routines
    WHERE routine_name LIKE 'search_documents%'
    AND routine_schema = 'public';

    SELECT COUNT(*) INTO index_count
    FROM pg_indexes
    WHERE tablename = 'document_embeddings'
    AND schemaname = 'public';

    RAISE NOTICE '=== Vector DB Seed Complete ===';
    RAISE NOTICE 'document_embeddings: % rows', doc_count;
    RAISE NOTICE 'Search functions:    %', func_count;
    RAISE NOTICE 'Indexes:             %', index_count;
    RAISE NOTICE '===============================';
END $$;

-- Distribution summary
SELECT
    metadata->>'failure_risk' AS failure_risk,
    COUNT(*) AS count,
    ROUND(AVG((metadata->>'health_score')::NUMERIC), 1) AS avg_health_score
FROM document_embeddings
WHERE document_type = 'equipment_health'
  AND metadata ? 'failure_risk'
GROUP BY metadata->>'failure_risk'
ORDER BY avg_health_score DESC;

COMMIT;

-- =============================================================================
-- Done. The vector_db now contains:
--   - 50 document_embeddings rows (equipment health reports + maintenance guides)
--   - 3 search functions (semantic, keyword, hybrid with RRF)
--   - GIN index on content_tsv for full-text search
--   - HNSW index on embedding for vector similarity (activates when embeddings added)
--   - Embeddings are NULL — run the indexing pipeline to populate them
-- =============================================================================
