-- ============================================================================
-- Equipment Health PostgreSQL Schema
-- Tables for the Equipment Health Agent to query via function tools.
-- Loaded from Parquet files generated by the predictive maintenance pipeline.
-- ============================================================================

-- Equipment Health Scores (from gold/equipment_health_scores.parquet)
-- One row per equipment with the latest ML prediction
CREATE TABLE IF NOT EXISTS equipment_health (
    equipment_id            TEXT PRIMARY KEY,
    plant_code              TEXT NOT NULL,
    production_line         TEXT,
    device_ids              TEXT,
    health_score            NUMERIC(5,2),
    failure_risk            TEXT CHECK (failure_risk IN ('Low', 'Medium', 'High', 'Critical')),
    failure_probability     NUMERIC(5,4),
    estimated_rul_days      INTEGER,
    last_maintenance_date   DATE,
    next_recommended_date   DATE,
    recommended_action      TEXT,
    anomaly_count_30d       INTEGER DEFAULT 0,
    top_risk_factors        JSONB,
    sensor_summary          JSONB,
    model_version           TEXT,
    computed_at             TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_eq_health_plant ON equipment_health (plant_code);
CREATE INDEX IF NOT EXISTS idx_eq_health_risk ON equipment_health (failure_risk);
CREATE INDEX IF NOT EXISTS idx_eq_health_score ON equipment_health (health_score);

-- IoT Telemetry (from bronze/iot/telemetry/iot_telemetry.parquet)
-- Sensor readings for equipment monitoring
CREATE TABLE IF NOT EXISTS iot_telemetry (
    id                      BIGSERIAL PRIMARY KEY,
    equipment_id            TEXT NOT NULL,
    device_id               TEXT NOT NULL,
    sensor_type             TEXT NOT NULL,
    reading_value           NUMERIC(10,4),
    reading_unit            TEXT,
    quality_flag            TEXT DEFAULT 'GOOD',
    reading_timestamp       TIMESTAMPTZ NOT NULL,
    plant_code              TEXT,
    production_line         TEXT
);

CREATE INDEX IF NOT EXISTS idx_telemetry_equip_time
    ON iot_telemetry (equipment_id, reading_timestamp DESC);
CREATE INDEX IF NOT EXISTS idx_telemetry_sensor
    ON iot_telemetry (sensor_type, reading_timestamp DESC);
CREATE INDEX IF NOT EXISTS idx_telemetry_anomaly
    ON iot_telemetry (quality_flag) WHERE quality_flag != 'GOOD';
CREATE INDEX IF NOT EXISTS idx_telemetry_plant
    ON iot_telemetry (plant_code);

-- Equipment Lifecycle Events (from bronze/iot/telemetry/equipment_lifecycle_events.parquet)
-- State transitions and maintenance records
CREATE TABLE IF NOT EXISTS equipment_lifecycle_events (
    id                      BIGSERIAL PRIMARY KEY,
    equipment_id            TEXT NOT NULL,
    event_type              TEXT NOT NULL,
    from_state              TEXT,
    to_state                TEXT,
    event_timestamp         TIMESTAMPTZ NOT NULL,
    plant_code              TEXT
);

CREATE INDEX IF NOT EXISTS idx_lifecycle_equip
    ON equipment_lifecycle_events (equipment_id, event_timestamp DESC);
